function Chicken() {
    Shape.call(this)

    this.setColor('gold')
    this.setHeight(200)
    this.setWidth(200)
    this.setRadius(50)
    this.setX(30)
    this.setY(145)

    var eyeL = new Shape()
    eyeL.setBorder(5, 'solid', 'LemonChiffon')
    eyeL.setWidth(30)
    eyeL.setHeight(30)
    eyeL.setRadius(50)
    eyeL.setColor('black')
    eyeL.setX(20)
    eyeL.setY(40)

    var eyeR = new Shape()
    eyeR.setBorder(5, 'solid', 'LemonChiffon')
    eyeR.setColor('black')
    eyeR.setX(90)
    eyeR.setY(40)
    eyeR.setRadius(50)
    eyeR.setWidth(30)
    eyeR.setHeight(30)

    var beak = new Shape()
    beak.setColor('orange')
    beak.setRadius(50)
    beak.setY(90)
    beak.setX(65)
    beak.setWidth(20)
    beak.setHeight(20)

    var face = new Shape()
    face.setColor('yellow')
    face.setRadius(50)
    face.setWidth(150)
    face.setHeight(150)
    face.setY(-120)
    face.setX(25)

    face.add(eyeL)
    face.add(eyeR)
    face.add(beak)

    var wingL = new Shape()
    wingL.setRotate(45)
    wingL.setColor('yellow')
    wingL.setRadius(50)
    wingL.setHeight(90)
    wingL.setWidth(50)
    wingL.setY(40)
    wingL.setX(-30)

    var wingR = new Shape()
    wingR.setRotate(-45)
    wingR.setColor('yellow')
    wingR.setRadius(50)
    wingR.setHeight(90)
    wingR.setWidth(50)
    wingR.setY(40)
    wingR.setX(180)

    var footL = new Shape()
    footL.setColor('orange')
    footL.setRadius(35)
    footL.setHeight(40)
    footL.setWidth(15)
    footL.setY(190)
    footL.setX(50)

    var footR = new Shape()
    footR.setColor('orange')
    footR.setRadius(35)
    footR.setHeight(40)
    footR.setWidth(15)
    footR.setY(190)
    footR.setX(130)

    var footL2 = new Shape()
    footL2.setColor('orange')
    footL2.setRadius(50)
    footL2.setHeight(15)
    footL2.setWidth(30)
    footL2.setY(220)
    footL2.setX(43)

    var footR2 = new Shape()
    footR2.setColor('orange')
    footR2.setRadius(50)
    footR2.setHeight(15)
    footR2.setWidth(30)
    footR2.setY(220)
    footR2.setX(124)

    this.add(wingL)
    this.add(wingR)
    this.add(face)
    this.add(footL)
    this.add(footR)
    this.add(footL2)
    this.add(footR2)
}

Chicken.prototype = Object.create(Shape.prototype)
Chicken.prototype.constructor = Chicken